src/Entity/Unavailability.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use App\Validator\Availability as UnavailabilityAssert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\UnavailabilityRepository")
 * @UnavailabilityAssert
 */
class Unavailability
{
    const   REUNION = 0,
            AUTRE = 1,
            ATTENTE="",
            VALIDER="";

    const   DAY_START = '08:00',
            DAY_END = '20:00';

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="datetime")
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $endDate;

    /**
     * @ORM\Column(type="string", length=80)
     * @Assert\NotBlank(message="Vous devez saisir un objet")
     * @Assert\Length(max="80", maxMessage="L'objet de la réunion ne doit pas dépasser {{ limit }} caractères.")
     */
    private $object;

     /**
     * @ORM\Column(type="string", length=80)
     * @Assert\NotBlank(message="Vous devez saisir un l'entité")
     * @Assert\Length(max="80", maxMessage="L'entité de la réunion ne doit pas dépasser {{ limit }} caractères.")
     */
    private $entite;
    /**
     * @ORM\Column(type="string", length=80)
     */
    private $etat;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TypeReservation", inversedBy="unavailabilities")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type_reservation;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="unavailabilities")
     * @ORM\JoinColumn(nullable=false)
     */
    private $organiser;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Room", inversedBy="unavailabilities")
     * @ORM\JoinColumn(nullable=false)
     */
    private $room;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="invitations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $guests;

    public function __construct()
    {
        $this->guests = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getObject(): ?string
    {
        return $this->object;
    }

    public function setObject(string $object): self
    {
        $this->object = $object;

        return $this;
    }
    public function getEntite(): ?string
    {
        return $this->entite;
    }

    public function setEntite(string $entite): self
    {
        $this->entite = $entite;

        return $this;
    }
    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }
    public function getTypeReservation(): ?TypeReservation
    {
        return $this->type_reservation;
    }

    public function setTypeReservation(?TypeReservation $type_reservation): self
    {
        $this->type_reservation = $type_reservation;

        return $this;
    }

    public function getOrganiser(): ?User
    {
        return $this->organiser;
    }

    public function setOrganiser(?User $organiser): self
    {
        $this->organiser = $organiser;

        return $this;
    }

    public function getRoom(): ?Room
    {
        return $this->room;
    }

    public function setRoom(?Room $room): self
    {
        $this->room = $room;

        return $this;
    }

    /**
     * Vérifie qu'un utilisateur est bien
     * l'organisateur de la réunion.
     * @param User|null $user
     * @return bool
     */
    public function isOrganiser(?User $user = null): bool
    {
        return $user && $this->getOrganiser()->getId() === $user->getId();
    }

    public function isNotPast()
    {
        return $this->getStartDate() > new \DateTime();
    }

    /**
     * @return Collection|User[]
     */
    public function getGuests(): Collection
    {
        return $this->guests;
    }

    public function isGuest(User $user) : bool
    {
        return $this->guests->contains($user);
    }

    public function addGuest(User $guest): self
    {
        if (!$this->guests->contains($guest)) {
            $this->guests[] = $guest;
        }

        return $this;
    }

    public function removeGuest(User $guest): self
    {
        if ($this->guests->contains($guest)) {
            $this->guests->removeElement($guest);
        }

        return $this;
    }
}

src/Form/UnavailabilityType.php
<?php

namespace App\Form;

use App\Entity\Unavailability;
use App\Entity\User;
use App\Repository\UserRepository;
use App\Entity\TypeReservation;
use App\Repository\TypeReservationRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;

class UnavailabilityType extends AbstractType
{
    protected $userRepository;
    protected $typereservationRepository;

    /**
     * UnavailabilityType constructor.
     * @param $userRepository
     * @param $typereservationRepository
     */
    public function __construct(UserRepository $userRepository,TypeReservationRepository $typereservationRepository)
    {
        $this->userRepository = $userRepository;
        $this->typereservationRepository = $typereservationRepository;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $users = $this->userRepository->findActiveUsersExceptCurrent();

        $builder
            ->add('object', TextType::class, [
                'label' => 'Objet'
            ])
            ->add('entite', TextType::class, [
                'label' => 'Entite'
            ])
            ->add('etat', HiddenType::class, [
                'data' => 'attente'
            ])
            
            ->add('guests', EntityType::class, [
                'label' => 'Invités',
                'class' => User::class,
                'choices' => $users,
                'choice_label' => function(User $user) {return $user->getFirstName().' '.$user->getLastName();},
                'multiple' => true
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Unavailability::class,
        ]);
    }
}

src/Controller/UnavailabilityController.php
<?php

namespace App\Controller;

use App\Entity\Room;
use App\Entity\Unavailability;
use App\Entity\TypeReservation;
use App\Entity\User;
use App\Form\UnavailabilityAdminType;
use App\Form\UnavailabilityEditAdminType;
use App\Form\UnavailabilityEditType;
use App\Form\TypeReservationType;
use App\Form\UnavailabilityType;
use App\Form\ImprimerPeriodeType;

use App\Repository\RoomRepository;
use App\Repository\UnavailabilityRepository;
use App\Service\EmailManager;
use App\Service\UnavailabilityManager;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Configuration;
use Doctrine\ORM\EntityManager;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Swift_Mailer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class UnavailabilityController extends AbstractController
{
    /**
     * Affiche les réunions organisées par l'utilisateur ou
     * toutes les réunions si l'utilisateur est admin.
     * @Route("/admin/historique.html", name="unavailability_index", methods={"GET"})
     * @return Response
     */
    public function index(): Response
    {
        $entityManager = $this->getDoctrine()->getManager();

        // On désactive le filtre pour obtenir les réunions organisées dans des salles supprimées,
        // ou dont l'organisateur ou un invité a été supprimé.
        $entityManager->getFilters()->disable('softdeleteable');

        $queryBuilder = $entityManager->createQueryBuilder()
            ->select('u')
            ->from(Unavailability::class, 'u')
            ->orderBy('u.startDate', 'DESC');

        $adapter = new DoctrineORMAdapter($queryBuilder);

        $pagerfanta = new Pagerfanta($adapter);

        if (isset($_GET["page"])) {
            $pagerfanta->setCurrentPage($_GET["page"]);
        }

        return $this->render('unavailability/index.html.twig', [
            'unavailabilities_pager' => $pagerfanta
        ]);
    }

    /**
     * Permet de créer une nouvelle réservation.
     * @Route("/nouvelle-reservation.html", name="unavailability_new", methods={"GET","POST"})
     * @IsGranted("ROLE_EMPLOYEE", message="Vous n'êtes pas autorisé à consulter cette page.")
     * @param Request $request
     * @param RoomRepository $roomRepository
     * @param \Swift_Mailer $mailer
     * @param UnavailabilityRepository $unavailabilityRepository
     * @param EmailManager $emailManager
     * @return Response
     */
    public function new(Request $request,
                        RoomRepository $roomRepository,
                        \Swift_Mailer $mailer,
                        UnavailabilityRepository $unavailabilityRepository,
                        EmailManager $emailManager): Response
    {
        $unavailability = new Unavailability();

        $typereservation = new TypeReservation();

        $unavailability->setOrganiser($this->getUser());

        if ($this->getUser()->hasRole('ROLE_ADMIN')) {
            $form = $this->createForm(UnavailabilityAdminType::class, $unavailability);
            $formType = $this->createForm(TypeReservationType::class, $typereservation);

            // Comme le formulaire admin a un champ Organiser, on l'indique.
            $form->get('organiser')->setData($this->getUser());
        } else {
            $form = $this->createForm(UnavailabilityType::class, $unavailability);
            $formType = $this->createForm(TypeReservationType::class, $typereservation);
          //  $unavailability->setTypeReservation("r");
        }

        // Pré-remplissage des dates et de la salle sélectionnées
        if (!null == $request->query->get('startDate')
            && !null == $request->query->get('endDate')
            && !null == $request->query->get('roomId')) {

            $startDate = \DateTime::createFromFormat('d/m/Y H:i', $request->query->get('startDate'));
            $endDate = \DateTime::createFromFormat('d/m/Y H:i', $request->query->get('endDate'));
            $room = $roomRepository->findOneById($request->query->get('roomId'));

            $unavailability ->setStartDate($startDate)
                            ->setEndDate($endDate)
                            ->setRoom($room);

//            $form->get('startDate')->setData($startDate);
//            $form->get('endDate')->setData($endDate);

            if ($this->getUser()->hasRole('ROLE_ADMIN')) {
                $form->get('room')->setData($room);
            }
        }

        $form->handleRequest($request);
        $formType->handleRequest($request);

        if ($formType->isSubmitted() && $formType->isValid()) {

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($typereservation);
            $entityManager->flush();

            $formData = $form->getData();

            return $this->redirect($request->getUri());
        }

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($unavailability);
            $entityManager->flush();

            $formData = $form->getData();

            // Envoi de mail à l'organisateur
            $emailManager->sendEmail($mailer,
                'Réservation Salle  | Enregistrement de votre réservation',
                $formData->getOrganiser()->getEmail(),
                'email/unavailability_new.html.twig',
                ['data' => $formData]
            );

            // Envoi de mails aux invités
            $guests = $formData->getGuests();
            foreach ($guests as $guest) {
                $emailManager->sendEmail($mailer,
                    'Réservation Salle  | Nouvelle invitation',
                    $guest->getEmail(),
                    'email/unavailability_new_guest.html.twig',
                    ['guest'=>$guest,'data' => $formData]
                );
            }

            $this->addFlash('notice',
                'La réservation a été enregistrée.');

            return $this->redirectToRoute('unavailability_calendar');
        }

//        $unavailabilities = $unavailabilityRepository->findUnavailabilitiesByRoom($room->getId());

        return $this->render('unavailability/new.html.twig', [
            'unavailability' => $unavailability,
            'form' => $form->createView(),
            'formType'=>$formType->createView()
//            'unavailabilities' => $unavailabilities,
        ]);
    }

    /**
     * Affiche les infos sur une réservation.
     * @Route("/reservation-{id}.html", name="unavailability_show", methods={"GET"})
     * @Security("unavailability != null", statusCode=404,
     *     message="Cette réservation n'existe plus ou n'a jamais existé.")
     * @Security("unavailability.isGuest(user) or has_role('ROLE_EMPLOYEE')", statusCode=403,
     *     message="Vous n'avez pas l'autorisation d'accéder à cette page.")
     * @param Unavailability $unavailability
     * @return Response
     */
    public function show(Unavailability $unavailability = null): Response
    {
        $em = $this->getDoctrine()->getManager();
        $em->getFilters()->disable('softdeleteable');

        return $this->render('unavailability/show.html.twig', [
            'unavailability' => $unavailability
        ]);
    }

    /**
     * Permet à l'admin ou à l'organisateur de modifier une réservation.
     * @Route("/modifier/reservation-{id}.html", name="unavailability_edit", methods={"GET","POST"})
     * @Security("unavailability != null", statusCode=404,
     *     message="Cette réservation n'existe plus ou n'a jamais existé.")
     * @Security("(unavailability.isOrganiser(user) or has_role('ROLE_ADMIN')) and unavailability.isNotPast()",
     *     message="Vous n'êtes pas autorisé à modifier cette réservation.")
     * @param Request $request
     * @param \Swift_Mailer $mailer
     * @param Unavailability $unavailability
     * @param EmailManager $emailManager
     * @return Response
     */
    public function edit(Request $request,
                         \Swift_Mailer $mailer,
                         Unavailability $unavailability = null,
                         EmailManager $emailManager): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->getFilters()->disable('softdeleteable');

        $typereservation = new TypeReservation();

        if ($this->getUser()->hasRole('ROLE_ADMIN')) {
            $form = $this->createForm(UnavailabilityEditAdminType::class, $unavailability);
            $formType = $this->createForm(TypeReservationType::class, $typereservation);

        } else {
            $form = $this->createForm(UnavailabilityEditType::class, $unavailability);
        }

        $oldGuests = $unavailability->getGuests()->toArray();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            $formData = $form->getData();

            // Envoi de mail à l'organisateur
            $emailManager->sendEmail($mailer,
                'Réservation Salle  | Modification de votre réservation',
                $formData->getOrganiser()->getEmail(),
                'email/unavailability_edit.html.twig',
                ['data' => $formData]
            );

            $newGuests = $unavailability->getGuests()->toArray();

            $persistGuests = [];
            $removedGuests = [];
            $additionalGuests = [];
            foreach ($oldGuests as $guest) {
                if (in_array($guest, $newGuests)) {
                    $persistGuests[] = $guest;
                } else {

templates/unavailability/_delete_form.html.twig
<form id="form" method="post" action="{{ path('unavailability_delete', {'id': unavailability.id}) }}" style="position: relative;float: right;bottom: 38px;">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ unavailability.id) }}">
    <button class="btn btn-warning" data-toggle="tooltip" data-placement="top" title="Supprimer">
        <i class="fas fa-trash-alt"></i>
    </button>
</form>

templates/unavailability/_form.html.twig
{{ form_start(form, {attr: {novalidate: 'novalidate'}}) }}

{{ form_label(form.object) }}
{{ form_widget(form.object) }}
{% if is_granted('ROLE_ADMIN')  %}
    {{ form_label(form.room) }}
    {{ form_widget(form.room) }}

    {{ form_label(form.type_reservation) }}
    {%block form_label%}

        <div> <button type="button" class="btn" data-toggle="modal" id="new_reserve_btn"><i class="fa fa-plus"></i> </button></div>

    {%endblock%}
    {{ form_widget(form.type_reservation) }}
    {{ form_label(form.organiser) }}
    {{ form_widget(form.organiser) }}

{% endif %}







{{ form_widget(form) }}



<button class="btn btn-info" style="margin-top: 20px;" data-toggle="tooltip" data-placement="top" title="Enregistrer">
    <i class="fas fa-check"></i>
</button>
<a href="{{ path('room_show', { 'id': unavailability.room.id }) }}" style="color: #fff;">
    <button type="button" class="btn btn-info" style="margin-top: 20px;" data-toggle="tooltip" data-placement="top" title="Retour">
        <i class="fas fa-chevron-left"></i>
    </button>
</a>
{{ form_end(form) }}

  {% include 'unavailability/new_type_reservation.html.twig' %}

{% block javascripts %}
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
    <script>
        $('#new_reserve_btn').on("click", function() {
            $.ajax({
                url: 'nouvelle-type-reservation.html',
                type: 'POST',
                dataType: 'html',
                success: function(code_html, statut){
                    $(code_html).appendTo('#modal_form');
                    $('#new_reserve').modal('show');
                }
            });
        });

    </script>
{% endblock %}

templates/unavailability/_form_type_reservation.html.twig
{{ form_start(form, {attr: {novalidate: 'novalidate'}}) }}

{{dump(form)}}

<button class="btn btn-info" style="margin-top: 20px;" data-toggle="tooltip" data-placement="top" title="Enregistrer">
    <i class="fas fa-check"></i>
</button>
{{ form_end(form) }}

templates/unavailability/edit.html.twig
{% extends 'layout.html.twig' %}

{% block page_title %}Modifier la réservation{% endblock %}

{% block content %}

    <div class="jumbotron col-md-6 mx-auto mt-4">

        <h1>Modifier la réservation</h1>

        {{ include('unavailability/_form.html.twig') }}

        <form id="form" method="post" action="{{ path('unavailability_delete', {'id': unavailability.id}) }}" style="position: relative;float: right;bottom: 38px;">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ unavailability.id) }}">
            <button class="btn btn-warning" data-toggle="tooltip" data-placement="top" title="Supprimer">
                <i class="fas fa-trash-alt"></i>
            </button>
        </form>

    </div>

    {% include 'components/_confirm_modal.html.twig' %}

{% endblock %}

{% set modal_message = 'Voulez-vous vraiment supprimer cette réservation ?' %}

{% block javascripts %}
    {{ parent() }}
    <script>
        $('#confirmationMessage').text('{{ modal_message }}');
        $('.modal-title').text('Supprimer la réservation');
        $('#form').click(function(e) {
            e.preventDefault();
            $('#confirmationModal').modal({});

            $('#confirm').on("click", function () {
                $('#form').submit();
                $("#confirmationModal").modal('hide');
            });

            $("#cancel").on("click", function(){
                $("#confirmationModal").modal('hide');
            });
        });
    </script>
{% endblock %}

templates/unavailability/index.html.twig
{% extends 'layout.html.twig' %}

{% block page_title %}Historique{% endblock %}

{% block content %}

    <div class="jumbotron col-md-9 mx-auto mt-4">

        <h1>Historique des réunions</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Objet</th>
                    <th>Salle</th>
                    <th>Organisateur</th>
                    <th>Début</th>
                    <th>Fin</th>
                    <th>Type</th>
                    <th>Etat</th>
                    <th> </th>
                </tr>
            </thead>
            <tbody>
            {% if unavailabilities_pager %}
            {% for unavailability in unavailabilities_pager %}
                <tr {{ unavailability.startDate < date() ? 'class="table-active "' : '' }}>
                    <td>{{ unavailability.object }}</td>
                    <td>{{ unavailability.room.name }}</td>
                    <td>{{ unavailability.organiser.firstName ~ ' ' ~ unavailability.organiser.lastName }}</td>
                    <td>Le {{ unavailability.startDate ? unavailability.startDate|date('d/m/Y à H:i') : '' }}</td>
                    <td>Le {{ unavailability.endDate ? unavailability.endDate|date('d/m/Y à H:i') : '' }}</td>
                    <td>{{ unavailability.typeReservation.name  }}</td>
                    <td><span class="{{unavailability.etat=='attente'?'btn btn-warning':'btn btn-success'}}">
                         {{ unavailability.etat }}</span></td>
                    <td class="last-column">
                        <a href="{{ path('unavailability_show', {'id': unavailability.id}) }}" style="text-decoration: none;">
                            <i class="fas fa-eye" data-toggle="tooltip" data-placement="top" title="Voir"></i>
                        </a>
                        {% if date() < unavailability.startDate %}
                        <a href="{{ path('unavailability_edit', {'id': unavailability.id}) }}">
                            <i class="fas fa-edit ml-2" data-toggle="tooltip" data-placement="top" title="Editer"></i>
                        </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            {% else %}
                <tr>
                    <td>Aucune réservation enregistrée.</td>
                </tr>
            {% endif %}
            </tbody>
        </table>
        {% if unavailabilities_pager and unavailabilities_pager.haveToPaginate %}
            {{ pagerfanta(unavailabilities_pager, 'reunion_it') }}
        {% endif %}
    </div>

{% endblock %}

templates/unavailability/new.html.twig
{% extends 'layout.html.twig' %}

{% block page_title %}Réservation{% endblock %}

{% block content %}

    <div class="jumbotron col-md-6 mx-auto mt-4">

        <h1>Réservation de la salle {{ unavailability.room.name }}</h1>
        <h3>du {{ unavailability.startDate | date('d/m/Y à H\\hi') ~ ' au ' ~ unavailability.endDate | date('d/m/Y à H\\hi') }}</h3>

        {{ include('unavailability/_form.html.twig') }}


    </div>

{% endblock %}

templates/unavailability/show.html.twig
{% extends 'layout.html.twig' %}

{% block page_title %}Réservation{% endblock %}

{% block content %}

    <div class="jumbotron col-md-9 mx-auto mt-4">

        <div class="d-flex">

            <h1 class="mr-auto">Réservation</h1>

            {% if is_granted('ROLE_EMPLOYEE') %}

            <div class="btn-group" role="group">
                <a href="{{ path('unavailability_calendar') }}" style="color: #fff;">
                    <button type="button" class="btn btn-info" style="width: 45px;" data-toggle="tooltip" data-placement="top" title="Calendrier">
                        <i class="fas fa-chevron-left"></i>
                    </button>
                </a>
                {% if is_granted('ROLE_ADMIN') or unavailability.organiser == app.user %}
                    {# On n'affiche les boutons 'edit' et 'delete' seulement si la réunion n'a pas commencé #}
                    {% if date() < date(unavailability.startDate) %}
                        <a href="{{ path('unavailability_edit', {'id': unavailability.id}) }}" style="color: #fff;">
                            <button type="button" class="btn btn-info" style="width: 45px;margin-left: 5px;">
                                <i class="fas fa-edit"></i>
                            </button>
                        </a>
                        <form id="form" method="post" action="{{ path('unavailability_delete', {'id': unavailability.id}) }}" style="display: inline-block;">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ unavailability.id) }}">
                            <button class="btn btn-warning" style="width: 45px;margin-left: 5px;">
                                <i class="fas fa-trash-alt"></i>
                            </button>
                        </form>
                    {% endif %}

                {% endif %}

            </div>

            {% endif %}
        </div>
        <table class="table">
            <tbody>
                <tr>
                    <th>Objet</th>
                    <td>{{ unavailability.object }}</td>
                </tr>
                <tr>
                    <th>Organisateur</th>
                    <td>
                        {# On désactive le lien vers l'organisateur s'il n'existe plus #}
                        {% if null == unavailability.organiser.deletedAt %}
                            <a href="{{ path('user_show', {'id': unavailability.organiser.id}) }}">
                                {{ unavailability.organiser.firstName ~ ' ' ~ unavailability.organiser.lastName }}
                            </a>
                        {% else %}
                            <span data-toggle="tooltip" data-placement="top" title="Compte supprimé">
                                {{ unavailability.organiser.firstName ~ ' ' ~ unavailability.organiser.lastName }}
                            </span>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <th>Entité</th>
                    <td>{{ unavailability.entite }}</td>
              
                </tr>
                <tr>
                    <th>Salle</th>
                    <td>
                        {# On désactive le lien vers la salle si elle n'existe plus #}
                        {% if null == unavailability.room.deletedAt %}
                            <a href="{{ path('room_show', {'id': unavailability.room.id}) }}">
                                {{ unavailability.room.name }}
                            </a>
                        {% else %}
                            {{ unavailability.room.name }}
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <th>Début</th>
                    <td>{{ unavailability.startDate ? unavailability.startDate|date('\\L\\e d/m/Y à H:i') : '' }}</td>
                </tr>
                <tr>
                    <th>Fin</th>
                    <td>{{ unavailability.endDate ? unavailability.endDate|date('\\L\\e d/m/Y à H:i') : '' }}</td>
                </tr>
                <tr>
                    <th>Invités</th>
                    <td>
                        {% for guest in unavailability.guests %}
                            {# On désactive le lien vers l'utilisateur s'il n'existe plus #}
                            {% if null == guest.deletedAt %}
                            <a href="{{ path('user_show', {'id': guest.id}) }}">
                                {{ guest.firstName ~ ' ' ~ guest.lastName }}{% if not loop.last %}, {% endif %}
                            </a>
                            {% else %}
                                <span data-toggle="tooltip" data-placement="top" title="Compte supprimé">
                                    {{ guest.firstName ~ ' ' ~ guest.lastName }}{% if not loop.last %}, {% endif %}
                                </span>
                            {% endif %}
                        {% endfor %}
                    </td>
                </tr>
                 <tr>
                    <th>Etat</th>
                    <td><span class="{{unavailability.etat=='attente'?'btn btn-warning':'btn btn-success'}}">
                          {{ unavailability.etat }}</span></td>
              
                </tr>
                {% if is_granted('ROLE_ADMIN') %}
                    <tr>
                        <th>Type</th>
                        <td>{{ unavailability.typeReservation.name }}</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>

    </div>

    {% include 'components/_confirm_modal.html.twig' %}

{% endblock %}

{% set modal_message = 'Voulez-vous vraiment supprimer cette réservation ?' %}

{% block javascripts %}
    {{ parent() }}
    <script>
        $('#confirmationMessage').text('{{ modal_message }}');
        $('.modal-title').text('Supprimer la réservation');
        $('#form').click(function(e) {
            e.preventDefault();
            $('#confirmationModal').modal({});

            $('#confirm').on("click", function () {
                $('#form').submit();
                $("#confirmationModal").modal('hide');
            });

            $("#cancel").on("click", function(){
                $("#confirmationModal").modal('hide');
            });
        });
    </script>
{% endblock %}